# See http://www.appveyor.com/docs/appveyor-yml for reference

#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  NUGET_RELEASE_VERSION: 1.0.2
  NUGET_FILE: Mayflower\Mayflower.nuspec
  ASSEMBLY_FILE: Mayflower\Properties\AssemblyInfo.cs

version: $(NUGET_RELEASE_VERSION).{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

assembly_info:
  patch: true
  file: $(ASSEMBLY_FILE)
  assembly_version: $(MAJOR_VERSION)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(NUGET_VERSION)

install:
  - ps: Scripts\SetNugetVersion.ps1
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  project: Mayflower.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

before_build:
  - nuget restore

#---------------------------------#
#       tests configuration       #
#---------------------------------#



#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: MayflowerCLI\bin\$(configuration)\mayflower.exe

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: ydv4d6HcjbsqPmSqA1/TJgj8HpG1S2tqOBfz+h7P/hYT/640tguzpkSPeDrOz4MW
    artifact: /^.*(\.nupkg|mayflower\.exe)$/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

#  # for pre-release versions
#  - provider: NuGet
#    api_key:
#      secure: H5jmXKutTu22M4cFiVnFnuGG0aZMcIhyv7k+IXLDuT+X8jr3Usk5bnAlOcFEEkp8
#    artifact: /.*\.nupkg/
#    skip_symbols: false
#    on:
#      branch: master

  # for release versions
  - provider: NuGet
    api_key:
      secure: H5jmXKutTu22M4cFiVnFnuGG0aZMcIhyv7k+IXLDuT+X8jr3Usk5bnAlOcFEEkp8
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true

